# XGBoost with silicon isotopes

In [45]:
# Imports
import joblib
import pandas as pd

from numpy import loadtxt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

## Read the CSV

In [49]:
# load data
#dataset = loadtxt('presolargrains_C_only.csv', delimiter=",")
# Read csv file
silicon = pd.read_csv('presolargrains_Si_for_SVM.csv')
silicon.head()

  Type  silicon_29_28  silicon_30_28
0    X         -662.0         -770.0
1    X         -451.0         -719.0
2    X         -594.0         -717.0
3    X         -499.0         -709.0
4    X         -366.0         -705.0

## Train Test Split

In [51]:
# split data into X and y
#X = carbon_nitrogen['carbon_12_13', 'nitrogen_14_15']
X = silicon.loc[::1,'silicon_29_28':'silicon_30_28']
y = silicon['Type'] #.values.reshape(-1, 1)
print(X)

       silicon_29_28  silicon_30_28
0             -662.0        -770.00
1             -451.0        -719.00
2             -594.0        -717.00
3             -499.0        -709.00
4             -366.0        -705.00
5             -455.0        -705.00
6             -514.0        -704.00
7             -357.0        -703.00
8             -269.0        -699.00
9             -555.0        -694.00
10            -350.0        -691.00
11            -563.0        -669.00
12            -345.0        -668.00
13            -474.0        -667.00
14            -492.0        -666.00
15            -531.0        -659.00
16            -485.0        -658.00
17            -279.0        -658.00
18            -406.0        -658.00
19            -335.0        -647.14
20            -569.0        -647.00
21            -392.0        -640.00
22            -343.0        -634.00
23            -286.0        -630.00
24            -521.0        -628.00
25            -307.0        -626.00
26            -492.0        -624.00
27            -374.0        -620.00
28            -428.0        -617.00
29            -645.0        -612.00
...              ...            ...
14649           80.0         376.00
14650          313.0         377.00
14651           58.0         383.00
14652         -108.0         392.00
14653          422.0         397.00
14654           93.0         399.00
14655          429.0         408.00
14656          -96.0         417.00
14657          413.0         422.00
14658           71.0         435.00
14659         -269.0         455.00
14660         -438.0         510.00
14661          -81.0         513.00
14662           96.0         609.00
14663         1149.0         826.00
14664         -154.0         874.00
14665         -166.0         927.00
14666         1280.0        1007.00
14667          996.0        1010.00
14668           79.0        1056.00
14669           28.0        1118.00
14670         1082.0        1207.00
14671         1362.0        1245.00
14672         1345.0        1272.00
14673         1608.0        1283.00
14674          800.0        1367.00
14675         2530.0        2108.00
14676         1811.0        2882.00
14677         2677.0        3287.00
14678          125.0        5650.00

[14679 rows x 2 columns]

In [52]:
# Split data into train and test sets
seed = 1
test_size = 0.33
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

## Fit model

In [53]:
# fit model
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
       importance_type='gain', interaction_constraints=None,
       learning_rate=0.300000012, max_delta_step=0, max_depth=6,
       min_child_weight=1, missing=nan, monotone_constraints=None,
       n_estimators=100, n_jobs=0, num_parallel_tree=1,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=None, subsample=1, tree_method=None,
       validate_parameters=False, verbosity=None)

## Print model

In [54]:
# Print model
print(model)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
       importance_type='gain', interaction_constraints=None,
       learning_rate=0.300000012, max_delta_step=0, max_depth=6,
       min_child_weight=1, missing=nan, monotone_constraints=None,
       n_estimators=100, n_jobs=0, num_parallel_tree=1,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=None, subsample=1, tree_method=None,
       validate_parameters=False, verbosity=None)

## Compare predictions to actual

In [55]:
# Make predictions for test data
y_pred = model.predict(X_test)
# Create and print dataframe with predicted and actual types
pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)

     Prediction Actual
0             Z      Z
1             M     AB
2             M      M
3             M      M
4             M      M
5             M      M
6             M      M
7             M      M
8             M      M
9             M      M
10            M      M
11            M      M
12            M      M
13            Z      M
14            M     AB
15            M      M
16            M      M
17            M      M
18            M      M
19            M      M
20            X      X
21            M      M
22            M      M
23            M      M
24            M      M
25            Z      Z
26            M      M
27            M      M
28            M      M
29            M      M
...         ...    ...
3640          M      M
3641          M      M
3642          M      M
3643          M      M
3644          M      M
3645          M      M
3646          M      M
3647          M      M
3648          M      M
3649          M      M
3650          M      M
3651          M      M
3652          M      M
3653          M      M
3654          Z      M
3655          M      M
3656          M      M
3657          M      M
3658          M      M
3659          M      M
3660          M      M
3661          M      M
3662          M      M
3663          M      M
3664          M      M
3665          M      Y
3666         AB      M
3667          M      M
3668          M      M
3669          M      M

[3670 rows x 2 columns]

## Report Accuracy

In [56]:
# Evaluate predictions
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 87.82%

In [57]:
# Not saving this model. Silicon alone is proving not to be the best way to classify this meteorite dataset as a whole.
#filename = 'XGBoost_Si.sav'
#joblib.dump(model, filename)

## Summary:

### XGBoost with silicon isotopes: 87.2%