# XGBoost with carbon and nitrgen isotopes

In [1]:
# Imports
import pandas as pd

from numpy import loadtxt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/anaconda3/lib/python3.7/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)

## Read the CSV

In [32]:
# load data
#dataset = loadtxt('presolargrains_C_only.csv', delimiter=",")
# Read csv file
carbon_nitrogen = pd.read_csv('presolargrains_C_N.csv')
carbon_nitrogen.head()

  Type  carbon_12_13  nitrogen_14_15
0   AB          1.57            59.0
1   AB          1.88            67.0
2   AB          1.94            78.0
3   AB          1.96            80.0
4   AB          2.15           118.0

## Train Test Split

In [21]:
# split data into X and y
#X = carbon_nitrogen['carbon_12_13', 'nitrogen_14_15']
X = carbon_nitrogen.loc[::1,'carbon_12_13':'nitrogen_14_15']
y = carbon_nitrogen['Type'] #.values.reshape(-1, 1)
#print(y)

In [22]:
# Split data into train and test sets
seed = 1
test_size = 0.33
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

## Fit model

In [23]:
# fit model
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
       importance_type='gain', interaction_constraints=None,
       learning_rate=0.300000012, max_delta_step=0, max_depth=6,
       min_child_weight=1, missing=nan, monotone_constraints=None,
       n_estimators=100, n_jobs=0, num_parallel_tree=1,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=None, subsample=1, tree_method=None,
       validate_parameters=False, verbosity=None)

## Print model

In [24]:
# Print model
print(model)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
       importance_type='gain', interaction_constraints=None,
       learning_rate=0.300000012, max_delta_step=0, max_depth=6,
       min_child_weight=1, missing=nan, monotone_constraints=None,
       n_estimators=100, n_jobs=0, num_parallel_tree=1,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=None, subsample=1, tree_method=None,
       validate_parameters=False, verbosity=None)

## Compare predictions to actual

In [28]:
# Make predictions for test data
y_pred = model.predict(X_test)
# Create and print dataframe with predicted and actual types
pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)

    Prediction Actual
0           AB     AB
1            M      Z
2            M      M
3           AB     AB
4            M      M
5            M      M
6           AB     AB
7            M      M
8           AB     AB
9            Y      Y
10           M      M
11           M      M
12           M      M
13           M      M
14          AB     AB
15           M      M
16           M      M
17           M      M
18           M      M
19           M      M
20           M      M
21           M      M
22           M      Z
23           M      M
24           Y      Y
25           M      M
26           X      X
27          AB     AB
28           Z      M
29          AB     AB
..         ...    ...
518          M      M
519          M      M
520          M      M
521          M      M
522          M      M
523         AB      X
524          M      M
525         AB     AB
526          M      M
527          M      M
528          M      M
529          M      M
530          M      M
531          M      M
532          X      X
533          X      X
534          M      M
535          M      M
536          M      M
537          M      M
538          M      M
539          M      M
540          M      M
541          M      M
542         AB     AB
543          M      M
544          M      M
545          M      M
546          M      M
547          M      M

[548 rows x 2 columns]

## Report Accuracy

In [30]:
# Evaluate predictions
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 95.80%

## Summary:

### XGBoost with carbon and nitrogen isotopes: 95.8%