# XGBoost with carbon, silicon, nitrogen, and aluminum isotopes  TEST NOTEBOOK

This notebook contains label encoding and then inverse, in other words: taking string data, converting it to numerical (for calculations), then converting it back to letters again.

In [21]:
# Imports
import joblib
import pandas as pd
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder

from numpy import loadtxt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

## Read the CSV

In [13]:
# load data
#dataset = loadtxt('presolargrains_C_only.csv', delimiter=",")
# Read csv file
C_Si_N_Al = pd.read_csv('presolargrains_C_Si_N_Al.csv')
C_Si_N_Al.head()

,Type,carbon_12_13,nitrogen_14_15,aluminum_26_27,silicon_29_28,silicon_30_28
0,X,1581.00,116.0,0.0095,-684.0,-490.0
1,X,234.75,187.2,0.3327,-683.0,-501.0
2,X,140.00,97.0,0.0170,-653.0,-446.0
3,X,223.00,102.0,0.1140,-600.0,-459.0
4,X,1693.89,63.2,0.2364,-588.0,-605.0

## Train Test Split

In [15]:
# split data into X and y
X = C_Si_N_Al.loc[::1,'carbon_12_13':'silicon_30_28']
y = C_Si_N_Al['Type'].values.reshape(-1, 1)
print(X)

     carbon_12_13  nitrogen_14_15  aluminum_26_27  silicon_29_28  \
0         1581.00          116.00        0.009500        -684.00
1          234.75          187.20        0.332700        -683.00
2          140.00           97.00        0.017000        -653.00
3          223.00          102.00        0.114000        -600.00
4         1693.89           63.20        0.236400        -588.00
5          216.59          111.72        0.000030        -556.53
6         2377.19           18.50        0.435700        -555.00
7          578.92          148.16        0.089000        -551.00
8         3101.02           28.20        0.437000        -521.00
9            6.48           15.77        0.390000        -489.00
10         552.00           58.00        0.204900        -473.30
11         304.00          106.00        0.230000        -459.00
12         391.00           39.00        0.167000        -452.00
13        1528.00           46.00        0.066000        -450.00
14          43.90           20.50        0.106000        -448.00
15           4.02           11.61        0.270000        -438.00
16        1026.00           88.00        0.239000        -436.00
17         448.00           69.00        0.134000        -430.00
18         149.26           61.98        0.302000        -428.00
19          26.10           29.20        0.173000        -410.00
20        1721.00           56.90        0.190000        -404.00
21          77.00          102.00        0.006300        -391.00
22          81.84           69.64        0.380083        -387.00
23         693.38          124.40        0.119200        -382.00
24        1549.52           60.00        0.471300        -381.00
25        1135.00           18.10        0.200000        -376.00
26         765.00           68.00        0.311000        -370.00
27         151.20           56.70        0.066000        -365.00
28        2525.00           12.60        0.610000        -363.00
29          50.20          107.10        0.053200        -360.00
..            ...             ...             ...            ...
298         23.58         2041.00        0.000190          92.40
299         52.39         2144.00        0.001330          95.00
300         51.64         2184.00        0.001470          95.00
301          8.74          917.00        0.000870          96.00
302        203.00          718.00        0.004000          95.80
303         51.54         1138.00        0.000550          96.00
304         56.00         5814.00        0.000860          98.50
305         50.80         2801.00        0.000600          99.90
306          4.50         1689.00        0.003900         101.70
307         51.86         2566.00        0.000610         103.00
308         57.91         2709.00        0.000630         106.00
309         62.30         2000.00        0.000220         107.00
310         59.85         1008.00        0.000550         115.00
311         44.00         1153.00        0.001300         120.00
312         96.80           34.50        0.035000         124.00
313         47.50         4386.00        0.001240         128.30
314         43.20          978.28        0.000361         140.00
315         43.10          481.00        0.001350         141.80
316         54.99         1231.00        0.000270         142.00
317         43.15         1915.00        0.000310         145.00
318         47.74          442.83        0.001213         146.00
319         41.89          445.00        0.000410         151.00
320         45.10          785.89        0.001298         156.00
321         43.79         2151.00        0.000150         160.00
322         42.69         1053.00        0.000700         164.00
323         41.30         3597.00        0.000840         168.30
324          7.74          446.00        0.001280         201.00
325         74.17          332.61        0.000914         577.00
326        108.93          147.00        0.122000        1082.00
327        192.03           58.40        0.001700        1345.00

     silicon_30_28
0          -490.00
1          -501.00
2          -446.00
3          -459.00
4          -605.00
5          -317.31
6          -694.00
7          -472.00
8          -467.00
9          -491.00
10         -501.90
11         -454.00
12         -387.00
13         -348.00
14         -535.00
15          510.00
16         -494.00
17         -572.00
18         -456.00
19         -568.00
20         -508.00
21         -510.00
22         -379.00
23         -553.00
24         -589.00
25         -585.00
26         -493.00
27         -491.00
28         -529.00
29         -359.00
..             ...
298         193.20
299          91.00
300          80.00
301          82.00
302         183.40
303          83.00
304          86.20
305          79.40
306          63.80
307          50.00
308          75.00
309          93.90
310          90.00
311         102.10
312        -363.00
313         104.90
314         112.00
315         107.70
316         102.00
317         119.00
318         111.00
319         124.00
320        -446.00
321         135.00
322         119.00
323         141.90
324         132.00
325        -187.00
326        1207.00
327        1272.00

[328 rows x 5 columns]

In [25]:
# Label Encoder and Transform
label_encoder = LabelEncoder()

data = y.copy()

label_encoder.fit(data)
encoded_y = label_encoder.transform(data)
label_encoder.classes_
encoded_y

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 4, 4, 4, 4, 4, 4, 6, 6, 2,
       2, 0, 2, 0, 2, 0, 0, 2, 2, 4, 2, 0, 2, 0, 0, 5, 2, 2, 6, 2, 2, 2,
       0, 5, 5, 0, 2, 0, 2, 0, 2, 0, 0, 6, 5, 0, 2, 2, 0, 5, 2, 0, 0, 0,
       0, 0, 0, 0, 5, 2, 2, 2, 0, 2, 0, 0, 0, 2, 2, 2, 0, 0, 5, 0, 5, 5,
       0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 5, 2, 2, 5, 2, 0, 0, 0, 2, 2, 0, 2,
       5, 0, 0, 5, 5, 2, 2, 5, 2, 0, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0,
       0, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 3, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 0, 0, 5, 2, 2, 5, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2,
       2, 0, 0, 5, 0, 0, 2, 2, 0, 2, 2, 2, 6, 2, 2, 0, 5, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 1])

In [26]:
# Split data into train and test sets
#seed = 1
#test_size = 0.33
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=seed)
X_train, X_test, y_train, y_test = train_test_split(X, encoded_y, random_state=1, stratify=y)

## Fit model

In [27]:
# fit model
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
       importance_type='gain', interaction_constraints=None,
       learning_rate=0.300000012, max_delta_step=0, max_depth=6,
       min_child_weight=1, missing=nan, monotone_constraints=None,
       n_estimators=100, n_jobs=0, num_parallel_tree=1,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=None, subsample=1, tree_method=None,
       validate_parameters=False, verbosity=None)

## Print model

In [28]:
# Print model
print(model)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
       importance_type='gain', interaction_constraints=None,
       learning_rate=0.300000012, max_delta_step=0, max_depth=6,
       min_child_weight=1, missing=nan, monotone_constraints=None,
       n_estimators=100, n_jobs=0, num_parallel_tree=1,
       objective='multi:softprob', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=None, subsample=1, tree_method=None,
       validate_parameters=False, verbosity=None)

## Compare predictions to actual

In [29]:
# Make predictions for test data
y_pred = model.predict(X_test)
# Create and print dataframe with predicted and actual types
pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)

    Prediction  Actual
0            0       0
1            2       2
2            2       2
3            4       4
4            2       2
5            5       5
6            2       2
7            2       2
8            4       4
9            0       0
10           2       2
11           2       2
12           0       0
13           4       4
14           4       4
15           0       0
16           4       4
17           5       5
18           4       4
19           4       4
20           2       2
21           5       5
22           4       4
23           2       2
24           4       4
25           0       0
26           2       2
27           0       0
28           2       2
29           4       4
..         ...     ...
52           0       0
53           2       2
54           4       4
55           0       0
56           2       2
57           2       2
58           0       3
59           2       4
60           0       0
61           0       0
62           2       2
63           2       2
64           2       2
65           5       5
66           2       2
67           0       0
68           2       2
69           2       2
70           2       2
71           0       0
72           4       4
73           0       0
74           2       0
75           0       0
76           2       2
77           2       2
78           2       2
79           2       2
80           4       4
81           2       2

[82 rows x 2 columns]

## Report Accuracy

In [30]:
# Evaluate predictions
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 95.12%

In [9]:
# Not saving this model. There are so few records (328) when using all these elements and removing empty cells
#filename = 'XGBoost_Si.sav'
#joblib.dump(model, filename)

## Summary:

### XGBoost with carbon, silicon, nitrogen, and aluminum isotopes: 95.1%

In [35]:
# Convert numbers back to letters
inverse = label_encoder.inverse_transform(y_test)
inverse
inverse_pred = label_encoder.inverse_transform(y_pred)

In [36]:
# Create and print dataframe with predicted and actual types
pd.DataFrame({"Prediction": inverse_pred, "Actual": inverse}).reset_index(drop=True)

   Prediction Actual
0          AB     AB
1           M      M
2           M      M
3           X      X
4           M      M
5           Y      Y
6           M      M
7           M      M
8           X      X
9          AB     AB
10          M      M
11          M      M
12         AB     AB
13          X      X
14          X      X
15         AB     AB
16          X      X
17          Y      Y
18          X      X
19          X      X
20          M      M
21          Y      Y
22          X      X
23          M      M
24          X      X
25         AB     AB
26          M      M
27         AB     AB
28          M      M
29          X      X
..        ...    ...
52         AB     AB
53          M      M
54          X      X
55         AB     AB
56          M      M
57          M      M
58         AB      N
59          M      X
60         AB     AB
61         AB     AB
62          M      M
63          M      M
64          M      M
65          Y      Y
66          M      M
67         AB     AB
68          M      M
69          M      M
70          M      M
71         AB     AB
72          X      X
73         AB     AB
74          M     AB
75         AB     AB
76          M      M
77          M      M
78          M      M
79          M      M
80          X      X
81          M      M

[82 rows x 2 columns]